[package]
name = "fasm"
version = "0.3.1"
edition = "2024"
authors = ["Azz <zk2u@pm.me>"]
description = "Fallible Async State Machines"
repository = "https://github.com/zk2u/fasm"
license = "MIT OR Apache-2.0"

[dependencies]

[dev-dependencies]
monoio = "0.2.4"

[workspace]
resolver = "3"
members = [
    "dentist_booking",
    "crates/fasm-storage",
    "crates/fasm-storage-btreemap",
    "crates/fasm-storage-redb",
    "crates/fasm-storage-fdb",
]

[workspace.package]
edition = "2024"
repository = "https://github.com/zk2u/fasm"
license = "MIT OR Apache-2.0"
publish = true

[workspace.dependencies]
fasm-storage = { path = "crates/fasm-storage" }
fasm-storage-btreemap = { path = "crates/fasm-storage-btreemap" }
fasm-storage-redb = { path = "crates/fasm-storage-redb" }
fasm-storage-fdb = { path = "crates/fasm-storage-fdb" }

async-trait = "0.1"
thiserror = "2"
proptest = "1.11"
redb = "2"
tokio = { version = "1", features = ["sync"] }
tracing = "0.1"
foundationdb = "0.11"
